version: '3'
services:
  confluent-zookeeper-service:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  confluent-kafka-service:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOSTNAME: confluent-kafka-service
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://confluent-kafka-service:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - confluent-zookeeper-service
    networks:
      - kafka-network

  kafka-producer-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODE=producer
    # Add any other configuration required for the Kafka producer container
    depends_on:
      - confluent-kafka-service
    networks:
      - kafka-network

  kafka-consumer-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODE=consumer
    # Add any other configuration required for the Kafka consumer container
    depends_on:
      - confluent-kafka-service
    networks:
      - kafka-network

networks:
  kafka-network:
